### ISSUE TITLE
Issue using mbedos5 target (nRF52840)

### ISSUE THREAD

**Issue by edbaafi** [pando-project/jerryscript#2569]
Hello,

The quickstart says you can:

git clone https://github.com/ARMmbed/mbed-js-example
cd mbed-js-example
npm install
gulp --target=YOUR_TARGET_NAME
However although the nRF52840 dev kit is claimed to be a supported board, running:

gulp --target=NRF52840_DK
fails with:

$ make BOARD=nrf52840_dk EXTRAS=
[15:39:30] build/make
[15:39:30] Finished 'build' after 2.63 s
[15:39:30] Starting 'default'...
[15:39:30] Finished 'default' after 86 μs
cd jerryscript/targets/mbedos5 && pip install -r tools/requirements.txt && rm -f source/js_encoded.cpp && rm -f source/pins.cpp && rm -f source/main.cpp && make BOARD=nrf52840_dk EXTRA_SRC="../../../source" EXTERN_BUILD_DIR=../../../out/nrf52840_dk NO_JS=1
Requirement already satisfied: pycparser<=2.17 in /usr/local/lib/python2.7/site-packages (from -r tools/requirements.txt (line 1)) (2.17)
Requirement already satisfied: simpleeval in /usr/local/lib/python2.7/site-packages (from -r tools/requirements.txt (line 2)) (0.9.6)
Requirement already satisfied: pycparserext in /usr/local/lib/python2.7/site-packages (from -r tools/requirements.txt (line 3)) (2016.2)
Requirement already satisfied: ply>=3.4 in /usr/local/lib/python2.7/site-packages (from pycparserext->-r tools/requirements.txt (line 3)) (3.11)
python tools/generate_pins.py nrf52840_dk
In file included from ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK13/device/nrf.h:74:0,
                 from ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK13/drivers_nrf/hal/nrf_gpio.h:41,
                 from ./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h:43:
./mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK13/device/nrf52840.h:143:10: fatal error: core_cm4.h: No such file or directory
 #include "core_cm4.h"                               /*!< Cortex-M4 processor and core peripherals                              */
          ^~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "tools/generate_pins.py", line 247, in <module>
    main()
  File "tools/generate_pins.py", line 240, in main
    pins = [(x, pins[x]) for x in pins]  # turn dict into tuples, which can be sorted
TypeError: 'NoneType' object is not iterable
make[1]: *** [source/pins.cpp] Error 1
make: *** [all] Error 2
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Command `make BOARD=nrf52840_dk EXTRAS=` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/user/Documents/GitHub/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at GulpRunner.afterTransform (_stream_transform.js:94:3)
    at ChildProcess.handleSubShellExit (/Users/user/Documents/GitHub/mbed-js-example/node_modules/gulp-run/command.js:169:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
Tried a few things including updating mbed-os from what is included by jerryscript but no luck. Any thoughts on a fix? Tends to be difficult to fix simple things like missing include dirs with all the magic Mbed CLI does and now with another layer of gulp, I thought I'd ask before trying to dig in further.

Thanks,
Ed

**Comment by edbaafi** [comment]
Picking this back up and realized this was not advertised as working with theNRF52840_DK but the NRF52_DK.   Closing this out and will open a new issue/pull-request if I can get a patch together for the NRF52840_DK

**Comment by ARM93** [comment]
> Picking this back up and realized this was not advertised as working with theNRF52840_DK but the NRF52_DK. Closing this out and will open a new issue/pull-request if I can get a patch together for the NRF52840_DK


Hi can you re-open this issue

**Comment by akosthekiss** [comment]
@ARM93 Could you be a bit more specific on the "why", please? If you have a new problem, you can open a new issue (with hopefully detailed descriptions).

**Comment by ARM93** [comment]
Because i have started to build the jerryscript for NRF52840 based on the command "gulp --target=NRF52840_DK" & faced the same issue . so that i asked you to re-open this issue.

**Comment by edbaafi** [comment]
@ARM93 As I stated above, this issue was not resolved but was closed because the developers never claimed this was working with the NRF52840_DK but actually the NRF52_DK.

I was able to get the blinky demo to compile but it did not actually work on the hardware and I didn't dig in further.  There are a lot of layers of magic happening with gulp/mbed-cli/mbed that I am not sure support through mbed is the right approach.  If I pick this back up I might just get it working directly with the NRF SDK to avoid a few layers of magic.

**Comment by ARM93** [comment]
> @ARM93 As I stated above, this issue was not resolved but was closed because the developers never claimed this was working with the NRF52840_DK but actually the NRF52_DK.
> 
> I was able to get the blinky demo to compile but it did not actually work on the hardware and I didn't dig in further. There are a lot of layers of magic happening with gulp/mbed-cli/mbed that I am not sure support through mbed is the right approach. If I pick this back up I might just get it working directly with the NRF SDK to avoid a few layers of magic.


@edbaafi Thanks for your replay.
