### ISSUE TITLE
Nominating Robert Fancsik (@rerobika) to become a JerryScript committer

### ISSUE THREAD

**Issue by akosthekiss** [pando-project/jerryscript#2676]
I would like to nominate Robert Fancsik (@rerobika) to become a committer. He already has 56 landed PRs (plus 11 currently under review).

https://github.com/pando-project/jerryscript/pulls?utf8=✓&q=is%3Apr+author%3Arerobika+

**Comment by LaszloLango** [comment]
+1

**Comment by robertsipka** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by yichoi** [comment]
+1

**Comment by akosthekiss** [comment]
Four seconds and no objections. Congrats to the successful nomination, @rerobika !
