### ISSUE TITLE
jerryscript on stm32l452re

### ISSUE THREAD

**Issue by wasi999** [pando-project/jerryscript#2761]
Hello friends,
 I want to run Jerryscript on stm32l452re with Zephyr as os. is there any successful implementation guide for it? because I searched and could not find one. if there is any please respond.
Thank you

**Comment by LaszloLango** [comment]
Hi @wasi999, project Zephyr.js is what you are looking for. Please check https://github.com/intel/zephyr.js
You can ask them of the supported boards as well. CC: @grgustaf

**Comment by wasi999** [comment]
thank you for your response
