### ISSUE TITLE
The size of snapshot from "jerry_generate_snapshot".

### ISSUE THREAD

**Issue by Becavalier** [pando-project/jerryscript#2826]
what does the "size of snapshot" mean here? Do you mean it's the byte length of the "buffer_p" array? Actually it must the integral times of uint32, corresponding to 4 bytes. But what I got is not.

![image](https://user-images.githubusercontent.com/8282020/56102005-ddd69100-5f5b-11e9-96fe-93009a68469a.png)

**Comment by LaszloLango** [comment]
@Becavalier Hi, the return size is the byte length of the snapshot. The reason  of the `uint32_t` output buffer is to ensure the buffer is aligned to 4 bytes. Unfortunately the documentation does not make it clear. I will update the description.

**Comment by Becavalier** [comment]
@LaszloLango Thanks, I get it. So the return value is the actual bytes length the snapshot used.
